[[redirects]]
  from = "https://year-review.jeremykamber.com/*"
  to = "https://script.google.com/macros/s/AKfycbzZD_zqvILD_BS3lBUWEVc-QHoXVpOJRLdydiK28f9-LpZnO7pG_F4g8L8_Ekvcgpoj/exec"
  status = 301
  force = true
